config/routes.rb
RedmineApp::Application.routes.draw do
  resources :issues, :only => [] do
    member do
      put :edit
    end
  end
  match '/projects/:project_id/issues/new', :to => 'issues#new', :as => 'switch_simple_mode_for_new', :via => :post
end

app/helpers/redmine_simple_helper.rb
module RedmineSimpleHelper
  def link_to_new_issue_simplify_on(project)
    link_to_new_issue_simplify_link(project, 'on')
  end

  def link_to_new_issue_simplify_off(project)
    link_to_new_issue_simplify_link(project, 'off')
  end

  def link_to_new_issue_simplify_link(project, simplify)
    raise ArgumentError('allowed only on|off values') unless simplify =~ /^on|off$/
    link_class = "simplify-#{simplify}"
    link_to l("text_simplify_#{simplify}"),
            switch_simple_mode_for_new_path(project.to_param),
            { :class => link_class }
  end

  def link_to_edit_issue_simplify_on(issue)
    link_to_edit_issue_simplify_link(issue, 'on')
  end

  def link_to_edit_issue_simplify_off(issue)
    link_to_edit_issue_simplify_link(issue, 'off')
  end

  def link_to_edit_issue_simplify_link(issue, simplify)
    raise ArgumentError('allowed only on|off values') unless simplify =~ /^on|off$/
    link_class = "simplify-#{simplify}"
    link_to l("text_simplify_#{simplify}"),
            edit_issue_path(issue),
            { :class => link_class }
  end

  def assignee_for_select(issue)
    # assignable_users + non_members
    data = { :more => false, :results => [] }
    members, groups = issue.assignable_users.sort.partition { |u| u.is_a? User }
    non_members = User.current.allowed_to?(:manage_members, issue.project) ?
        User.active.not_member_of(issue.project).sort : []

    # me
    data[:results] << user_to_select2_item(
        User.current,
        :text => "<< #{l(:label_me)} >>",
        :name => User.current.name
    )

    # author
    if User.current.id != issue.author.id
      data[:results] << user_to_select2_item(
          issue.author,
          :text => "<< #{l(:field_author)} >>",
          :name => issue.author.name
      )
    end

    # members
    data[:results] += members.map { |u| user_to_select2_item(u) }

    # groups
    if groups.any?
      data[:results] << {
          :text => l(:label_group),
          :children => groups.map { |u| user_to_select2_item(u) }
      }
    end

    # non members
    if non_members.any?
      data[:results] << {
          :text => l(:label_role_non_member),
          :children => non_members.map do |u|
            user_to_select2_item(u, :non_member => true)
          end
      }
    end
    data
  end

  def watchers_for_select(issue)
    # me, members + non_members
    data = { :more => false, :results => [] }

    member_ids = issue.project.users.pluck(:user_id).map(&:to_i)
    members, non_members =
        User.active.sort.partition { |u| member_ids.include?(u.id) }

    # me
    data[:results] << user_to_select2_item(
        User.current,
        :text => "<< #{l(:label_me)} >>",
        :name => User.current.name
    )

    # members
    data[:results] += members.map { |u| user_to_select2_item(u) }

    # non members
    if non_members.any?
      data[:results] << {
          :text => l(:label_role_non_member),
          :children => non_members.map do |u|
            user_to_select2_item(u, :non_member => true)
          end
      }
    end
    data
  end

  def user_to_select2_item(*args)
    options = args.extract_options!
    user = args[0]
    {
        :id => user.id,
        :text => user.name,
        :login => user.login,
        :email => user.mail
    }.merge(options)
  end
end

app/views/hooks/redmine_simple/_form_includes.html.erb
<% unless request.xhr? %>
  <%= javascript_include_tag 'simplify_filter', :plugin => 'redmine_simple' %>
  <%= javascript_include_tag 'simplify_assignee', :plugin => 'redmine_simple' %>
  <%= javascript_include_tag 'simplify_watchers', :plugin => 'redmine_simple' %>
  <%= javascript_include_tag 'simplify_links', :plugin => 'redmine_simple' %>
  <%= javascript_include_tag 'jquery.blockUI.min.js', :plugin => 'redmine_simple' %>
  <%= javascript_include_tag 'simplify_block_ui', :plugin => 'redmine_simple' %>
  <%= javascript_include_tag 'simplify_description', :plugin => 'redmine_simple' %>

  <%= javascript_tag do %>
    function showNewMemberModal(attrs) {
    <% if User.current.allowed_to? :manage_members, @project %>
      $("#ajax-modal").html('<%= escape_javascript(render 'simple/issues/new_member', :project => @project) %>');
      $('#membership_user_ids').val(attrs.memberId);
      $("#new-member-candidate").text(attrs.memberName);
      $("#member-add-cancel").on("click", attrs.cancel);
      $('input[name="membership[role_ids][]"]').on('change', function() {
        $('#member-add-submit').attr('disabled',
            $('input[name="membership[role_ids][]"]:checked').length < 1);
      });
      $('input[name="membership[role_ids][]"]:first').trigger('change');
      if (attrs.success) {
        $("#new-member-form").bind('ajax:success', function() {
          attrs.success.call();
        });
      }
      showModal("ajax-modal", "300px");
      $("#ajax-modal").addClass("new-member");
    <% end %>
    }
  <% end %>

<% end %>

app/views/hooks/redmine_simple/_includes.html.erb
<%= stylesheet_link_tag 'redmine_simple', :plugin => 'redmine_simple' %>

app/views/issues/_update_form.js.erb
<%= render :partial => 'update_form_replacement' %>

app/views/issues/_update_form_replacement.js.erb
<% if RedmineSimple.on? %>
$('#all_attributes').html('<%= escape_javascript(render :partial => 'simple/issues/form') %>');
<% else %>
$('#all_attributes').html('<%= escape_javascript(render :partial => 'form') %>');
<% end %>

<% if User.current.allowed_to?(:log_time, @issue.project) %>
$('#log_time').show();
<% else %>
$('#log_time').hide();
<% end %>

simplifyAssignee();

app/views/issues/update_form.js.erb
<%= render :partial => 'update_form_replacement' %>

app/views/simple/issues/_edit.html.erb
<%= labelled_form_for @issue, :html => {:id => 'issue-form', :multipart => true} do |f| %>
  <%= error_messages_for 'issue', 'time_entry' %>
  <%= render :partial => 'conflict' if @conflict %>
  <div class="simple-box tabular">
    <% if @edit_allowed || !@allowed_statuses.empty? %>
      <div id="all_attributes">
        <%= render 'simple/issues/form', {:f => f} %>
      </div>
      <div class="simple-hidden">
        <%= call_hook(:view_issues_edit_notes_bottom, { :issue => @issue, :notes => @notes, :form => f }) %>
      </div>
    <% end %>

    <div style="display: none;">
      <%= render :partial => 'attachments/form', :locals => {:container => @issue} %>
    </div>
  </div>


  <%= f.hidden_field :lock_version %>
  <%= hidden_field_tag 'last_journal_id', params[:last_journal_id] || @issue.last_journal_id %>
  <%= submit_tag l(:button_submit) %>
  <%= preview_link preview_edit_issue_path(:project_id => @project, :id => @issue), 'issue-form' %>
  <%= link_to_edit_issue_simplify_off(@issue) %>
<% end %>

<div id="preview" class="wiki"></div>

app/views/simple/issues/_form.html.erb
<%= labelled_fields_for :issue, @issue do |f| %>
  <div class="simple-hidden">
    <%= call_hook(:view_issues_form_details_top, { :issue => @issue, :form => f }) %>
  </div>

  <% if @issue.safe_attribute? 'tracker_id' %>
    <p><%= f.select :tracker_id, @issue.project.trackers.collect {|t| [t.name, t.id]}, {:required => true} %></p>
  <% end %>

  <% if @issue.safe_attribute? 'subject' %>
    <p>
      <%= f.text_field :subject,
                       :maxlength => 255,
                       :required => true %>
    </p>
  <% end %>

  <% if @issue.safe_attribute? 'assigned_to_id' %>
    <p>
      <label><%= l(:field_assigned_to) %></label>
      <%= f.hidden_field :assigned_to_id, :data => {
          :initial => assignee_for_select(@issue),
          :text => @issue.assigned_to.try(:name).to_s } %>
    </p>
  <% end %>

  <% if @issue.safe_attribute? 'description' %>
    <%= content_tag :p, :style => (@issue.persisted? ? 'display: none;' : nil), :class => 'no-label' do %>
      <%= f.text_area :description,
                      :no_label => true,
                      :cols => 80,
                      :rows => (@issue.description.blank? ? 10 : [[10, @issue.description.length / 50].max, 100].min),
                      :accesskey => accesskey(:edit),
                      :class => 'no-label' %>
    <% end %>
  <% end %>

  <% if @issue.persisted? %>
    <p>
      <% if @issue.safe_attribute?('status_id') && @allowed_statuses.present? %>
          <%= f.select :status_id, (@allowed_statuses.collect {|p| [p.name, p.id]}), {:required => true},
                       :onchange => "updateIssueFrom('#{escape_javascript project_issue_form_path(@project, :id => @issue, :format => 'js')}')" %>
      <% else %>
          <label><%= l(:field_status) %></label> <%= h(@issue.status.name) %>
      <% end %>
    </p>

    <% if @issue.safe_attribute?('done_ratio') && @issue.leaf? && Issue.use_field_for_done_ratio? %>
      <p><%= f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r*10} %", r*10] }), :required => @issue.required_attribute?('done_ratio') %></p>
    <% end %>

    <p class="no-label">
      <%= f.text_area :notes, :cols => 60, :rows => 10, :no_label => true, class: 'no-label', :value => @notes %>
    </p>
  <% end %>

  <!-- hidden attributes -->
  <div class="simple-hidden">
    <% hidden_fields = %w{is_private project_id priority_id category_id fixed_version_id parent_issue_id start_date due_date estimated_hours} %>
    <% hidden_fields << 'status_id' << 'done_ratio' unless @issue.persisted? %>
    <% hidden_fields.each do |field| %>
      <%= f.hidden_field field if @issue.safe_attribute? field %>
    <% end %>
    <% if @issue.safe_attribute? 'custom_field_values' %>
      <%= render :partial => 'issues/form_custom_fields' %>
    <% end %>
    <%= call_hook(:view_issues_form_details_bottom, { :issue => @issue, :form => f }) %>
  </div>

<% end %>

app/views/simple/issues/_new_member.html.erb
<h3 class="title"><%= l(:label_member_new) %></h3>

<%= form_tag(project_memberships_path(project),
             :remote => true,
             :method => :post,
             :id => 'new-member-form') do %>

  <p>
    <label id="new-member-candidate"></label>
    <%= l(:text_not_member_yet) %>
  </p>

  <input type="hidden" id="membership_user_ids" name="membership[user_ids][]">

  <div class="new-meber-roles">
    <% Role.find_all_givable.each do |role| %>
      <label><%= check_box_tag 'membership[role_ids][]', role.id %> <%=h role %></label><br/>
    <% end %>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_add),
                   :id => 'member-add-submit',
                   :name => nil,
                   :onclick => "hideModal(this);" %>
    <%= submit_tag l(:button_cancel),
                   :name => nil,
                   :id => 'member-add-cancel',
                   :onclick => "hideModal(this);",
                   :type => 'button' %>
  </p>
<% end %>

app/views/simple/issues/_watchers_form.html.erb
<p>
  <label><%= l(:label_issue_watchers) %></label>
  <%= f.hidden_field :select2_watcher_user_ids, :data => {
      :initial => watchers_for_select(@issue),
      :selected => @issue.watcher_users.map { |u| { :id => u.id, :text => u.name } } } %>
</p>

app/views/simple/issues/edit.html.erb
<h2><%=h "#{@issue.tracker.name} ##{@issue.id}" %></h2>

<%= render :partial => 'simple/issues/edit' %>
<% content_for :header_tags do %>
  <%= robot_exclusion_tag %>
<% end %>

app/views/simple/issues/new.html.erb
<%= labelled_form_for @issue, :url => project_issues_path(@project),
                      :html => {:id => 'issue-form', :multipart => true} do |f| %>
  <%= error_messages_for 'issue' %>
  <%= hidden_field_tag 'copy_from', params[:copy_from] if params[:copy_from] %>
  <div class="simple-box tabular">
    <div id="all_attributes">
      <%= render 'simple/issues/form', {:f => f} %>
    </div>

    <div style="display: none;">
      <% if @copy_from && @copy_from.attachments.any? %>
        <p>
          <label for="copy_attachments"><%= l(:label_copy_attachments) %></label>
          <%= check_box_tag 'copy_attachments', '1', @copy_attachments %>
        </p>
      <% end %>
      <% if @copy_from && !@copy_from.leaf? %>
        <p>
          <label for="copy_subtasks"><%= l(:label_copy_subtasks) %></label>
          <%= check_box_tag 'copy_subtasks', '1', @copy_subtasks %>
        </p>
      <% end %>

      <% if @issue.safe_attribute? 'watcher_user_ids' -%>
        <%= watchers_checkboxes(@issue, @available_watchers) %>
      <% end %>
    </div>

  </div>


  <div class="simple-buttons">
    <%= link_to_new_issue_simplify_off(@project) %>
    <%= submit_tag l(:button_create) %>
    <%= preview_link preview_new_issue_path(:project_id => @project), 'issue-form' %>
  </div>

  <%= javascript_tag "$('#issue_subject').focus();" %>
<% end %>

<div id="preview" class="wiki"></div>

<% content_for :header_tags do %>
  <%= robot_exclusion_tag %>
<% end %>